// 由 tool/generate_codec_descriptors.c 生成

#ifndef CODEC_DESCRIPTORS_H
#define CODEC_DESCRIPTORS_H

#include "qlist.h"
#include <qmap.h>

inline QMap<QString, QMap<QString, QList<QString>>> codec_supports = {
    {"a64", {{"video", {"a64_multi"}}, {"audio", {}}}},
    {" A64", {{"video", {"a64_multi"}}, {"audio", {}}}},
    {"ac3", {{"video", {}}, {"audio", {"ac3"}}}},
    {"ac4", {{"video", {}}, {"audio", {"ac4"}}}},
    {"aac", {{"video", {}}, {"audio", {"aac"}}}},
    {"adts", {{"video", {}}, {"audio", {"aac"}}}},
    {"adx", {{"video", {}}, {"audio", {"adpcm_adx"}}}},
    {"aea", {{"video", {}}, {"audio", {"atrac1"}}}},
    {"aif",
     {{"video", {}},
      {"audio",
       {"pcm_s16be",    "pcm_s8",       "pcm_u8",       "pcm_s24be",
        "pcm_s32be",    "pcm_f32be",    "pcm_f64be",    "pcm_alaw",
        "pcm_mulaw",    "mace3",        "mace6",        "gsm",
        "adpcm_g722",   "adpcm_g726le", "g728",         "pcm_s16le",
        "adpcm_ima_qt", "qdmc",         "qdm2",         "qcelp",
        "cbd2_dpcm",    "sdx2_dpcm",    "adpcm_ima_ws", "adpcm_n64"}}}},
    {"aiff",
     {{"video", {}},
      {"audio",
       {"pcm_s16be",    "pcm_s8",       "pcm_u8",       "pcm_s24be",
        "pcm_s32be",    "pcm_f32be",    "pcm_f64be",    "pcm_alaw",
        "pcm_mulaw",    "mace3",        "mace6",        "gsm",
        "adpcm_g722",   "adpcm_g726le", "g728",         "pcm_s16le",
        "adpcm_ima_qt", "qdmc",         "qdm2",         "qcelp",
        "cbd2_dpcm",    "sdx2_dpcm",    "adpcm_ima_ws", "adpcm_n64"}}}},
    {"afc",
     {{"video", {}},
      {"audio",
       {"pcm_s16be",    "pcm_s8",       "pcm_u8",       "pcm_s24be",
        "pcm_s32be",    "pcm_f32be",    "pcm_f64be",    "pcm_alaw",
        "pcm_mulaw",    "mace3",        "mace6",        "gsm",
        "adpcm_g722",   "adpcm_g726le", "g728",         "pcm_s16le",
        "adpcm_ima_qt", "qdmc",         "qdm2",         "qcelp",
        "cbd2_dpcm",    "sdx2_dpcm",    "adpcm_ima_ws", "adpcm_n64"}}}},
    {"aifc",
     {{"video", {}},
      {"audio",
       {"pcm_s16be",    "pcm_s8",       "pcm_u8",       "pcm_s24be",
        "pcm_s32be",    "pcm_f32be",    "pcm_f64be",    "pcm_alaw",
        "pcm_mulaw",    "mace3",        "mace6",        "gsm",
        "adpcm_g722",   "adpcm_g726le", "g728",         "pcm_s16le",
        "adpcm_ima_qt", "qdmc",         "qdm2",         "qcelp",
        "cbd2_dpcm",    "sdx2_dpcm",    "adpcm_ima_ws", "adpcm_n64"}}}},
    {"tun", {{"video", {}}, {"audio", {"adpcm_ima_alp"}}}},
    {"pcm", {{"video", {}}, {"audio", {"adpcm_ima_alp"}}}},
    {"amr", {{"video", {}}, {"audio", {"amr_nb"}}}},
    {"amv", {{"video", {"amv"}}, {"audio", {"adpcm_ima_amv"}}}},
    {"apm", {{"video", {}}, {"audio", {"adpcm_ima_apm"}}}},
    {"apng", {{"video", {"apng"}}, {"audio", {}}}},
    {"aptx", {{"video", {}}, {"audio", {"aptx"}}}},
    {"aptxhd", {{"video", {}}, {"audio", {"aptx_hd"}}}},
    {"apv", {{"video", {"apv"}}, {"audio", {}}}},
    {"cvg", {{"video", {}}, {"audio", {"adpcm_psx"}}}},
    {"asf",
     {{"video", {"mpeg4",      "msmpeg4v3",   "h264",          "h263",
                 "h263p",      "h263i",       "h261",          "msmpeg4v2",
                 "msmpeg4v1",  "wmv1",        "wmv2",          "dvvideo",
                 "mpeg1video", "mpeg2video",  "mjpeg",         "ljpeg",
                 "jpegls",     "avrn",        "huffyuv",       "ffvhuff",
                 "cyuv",       "rawvideo",    "frwu",          "r10k",
                 "r210",       "v210",        "v308",          "v408",
                 "v410",       "yuv4",        "indeo3",        "indeo4",
                 "indeo5",     "vp3",         "vp4",           "vp5",
                 "vp6",        "vp6a",        "vp6f",          "vp7",
                 "vp8",        "vp9",         "asv1",          "asv2",
                 "vcr1",       "ffv1",        "xan_wc4",       "mimic",
                 "msrle",      "msvideo1",    "cinepak",       "truemotion1",
                 "mszh",       "zlib",        "snow",          "4xm",
                 "flv1",       "flashsv",     "svq1",          "tscc",
                 "ulti",       "vixl",        "qpeg",          "wmv3",
                 "wmv3image",  "vc1",         "vc1image",      "loco",
                 "wnv1",       "aasc",        "indeo2",        "fraps",
                 "theora",     "truemotion2", "truemotion2rt", "cscd",
                 "zmbv",       "kmvc",        "cavs",          "avs2",
                 "jpeg2000",   "vmnc",        "targa",         "png",
                 "cljr",       "dirac",       "rpza",          "sp5x",
                 "aura",       "aura2",       "dpx",           "kgv1",
                 "lagarith",   "amv",         "utvideo",       "vble",
                 "escape130",  "dxtory",      "zerocodec",     "y41p",
                 "flic",       "mss1",        "msa1",          "tscc2",
                 "mts2",       "cllc",        "mss2",          "svq3",
                 "012v",       "g2m",         "fic",           "hqx",
                 "tdsc",       "hq_hqa",      "rv40",          "screenpresso",
                 "rscc",       "cfhd",        "m101",          "magicyuv",
                 "ylc",        "speedhq",     "fmvc",          "scpr",
                 "clearvideo", "av1",         "mscc",          "srgc",
                 "imm4",       "prosumer",    "mwsc",          "wcmv",
                 "rasc",       "hymt",        "arbc",          "agm",
                 "lscr",       "imm5",        "mvdv",          "mvha",
                 "mv30",       "notchlc",     "vqc",           "rtv1",
                 "vmix",       "lead",        "evc",           "rv60"}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis"}}}},
    {"wmv",
     {{"video", {"mpeg4",      "msmpeg4v3",   "h264",          "h263",
                 "h263p",      "h263i",       "h261",          "msmpeg4v2",
                 "msmpeg4v1",  "wmv1",        "wmv2",          "dvvideo",
                 "mpeg1video", "mpeg2video",  "mjpeg",         "ljpeg",
                 "jpegls",     "avrn",        "huffyuv",       "ffvhuff",
                 "cyuv",       "rawvideo",    "frwu",          "r10k",
                 "r210",       "v210",        "v308",          "v408",
                 "v410",       "yuv4",        "indeo3",        "indeo4",
                 "indeo5",     "vp3",         "vp4",           "vp5",
                 "vp6",        "vp6a",        "vp6f",          "vp7",
                 "vp8",        "vp9",         "asv1",          "asv2",
                 "vcr1",       "ffv1",        "xan_wc4",       "mimic",
                 "msrle",      "msvideo1",    "cinepak",       "truemotion1",
                 "mszh",       "zlib",        "snow",          "4xm",
                 "flv1",       "flashsv",     "svq1",          "tscc",
                 "ulti",       "vixl",        "qpeg",          "wmv3",
                 "wmv3image",  "vc1",         "vc1image",      "loco",
                 "wnv1",       "aasc",        "indeo2",        "fraps",
                 "theora",     "truemotion2", "truemotion2rt", "cscd",
                 "zmbv",       "kmvc",        "cavs",          "avs2",
                 "jpeg2000",   "vmnc",        "targa",         "png",
                 "cljr",       "dirac",       "rpza",          "sp5x",
                 "aura",       "aura2",       "dpx",           "kgv1",
                 "lagarith",   "amv",         "utvideo",       "vble",
                 "escape130",  "dxtory",      "zerocodec",     "y41p",
                 "flic",       "mss1",        "msa1",          "tscc2",
                 "mts2",       "cllc",        "mss2",          "svq3",
                 "012v",       "g2m",         "fic",           "hqx",
                 "tdsc",       "hq_hqa",      "rv40",          "screenpresso",
                 "rscc",       "cfhd",        "m101",          "magicyuv",
                 "ylc",        "speedhq",     "fmvc",          "scpr",
                 "clearvideo", "av1",         "mscc",          "srgc",
                 "imm4",       "prosumer",    "mwsc",          "wcmv",
                 "rasc",       "hymt",        "arbc",          "agm",
                 "lscr",       "imm5",        "mvdv",          "mvha",
                 "mv30",       "notchlc",     "vqc",           "rtv1",
                 "vmix",       "lead",        "evc",           "rv60"}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis"}}}},
    {"wma",
     {{"video", {"mpeg4",      "msmpeg4v3",   "h264",          "h263",
                 "h263p",      "h263i",       "h261",          "msmpeg4v2",
                 "msmpeg4v1",  "wmv1",        "wmv2",          "dvvideo",
                 "mpeg1video", "mpeg2video",  "mjpeg",         "ljpeg",
                 "jpegls",     "avrn",        "huffyuv",       "ffvhuff",
                 "cyuv",       "rawvideo",    "frwu",          "r10k",
                 "r210",       "v210",        "v308",          "v408",
                 "v410",       "yuv4",        "indeo3",        "indeo4",
                 "indeo5",     "vp3",         "vp4",           "vp5",
                 "vp6",        "vp6a",        "vp6f",          "vp7",
                 "vp8",        "vp9",         "asv1",          "asv2",
                 "vcr1",       "ffv1",        "xan_wc4",       "mimic",
                 "msrle",      "msvideo1",    "cinepak",       "truemotion1",
                 "mszh",       "zlib",        "snow",          "4xm",
                 "flv1",       "flashsv",     "svq1",          "tscc",
                 "ulti",       "vixl",        "qpeg",          "wmv3",
                 "wmv3image",  "vc1",         "vc1image",      "loco",
                 "wnv1",       "aasc",        "indeo2",        "fraps",
                 "theora",     "truemotion2", "truemotion2rt", "cscd",
                 "zmbv",       "kmvc",        "cavs",          "avs2",
                 "jpeg2000",   "vmnc",        "targa",         "png",
                 "cljr",       "dirac",       "rpza",          "sp5x",
                 "aura",       "aura2",       "dpx",           "kgv1",
                 "lagarith",   "amv",         "utvideo",       "vble",
                 "escape130",  "dxtory",      "zerocodec",     "y41p",
                 "flic",       "mss1",        "msa1",          "tscc2",
                 "mts2",       "cllc",        "mss2",          "svq3",
                 "012v",       "g2m",         "fic",           "hqx",
                 "tdsc",       "hq_hqa",      "rv40",          "screenpresso",
                 "rscc",       "cfhd",        "m101",          "magicyuv",
                 "ylc",        "speedhq",     "fmvc",          "scpr",
                 "clearvideo", "av1",         "mscc",          "srgc",
                 "imm4",       "prosumer",    "mwsc",          "wcmv",
                 "rasc",       "hymt",        "arbc",          "agm",
                 "lscr",       "imm5",        "mvdv",          "mvha",
                 "mv30",       "notchlc",     "vqc",           "rtv1",
                 "vmix",       "lead",        "evc",           "rv60"}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis"}}}},
    {"ass", {{"video", {}}, {"audio", {}}}},
    {"ssa", {{"video", {}}, {"audio", {}}}},
    {"ast", {{"video", {}}, {"audio", {"adpcm_afc", "pcm_s16be_planar"}}}},
    {"au",
     {{"video", {}},
      {"audio",
       {"pcm_mulaw", "pcm_s8", "pcm_s16be", "pcm_s24be", "pcm_s32be",
        "pcm_f32be", "pcm_f64be", "adpcm_g726le", "adpcm_g722", "pcm_alaw"}}}},
    {"avi",
     {{"video", {"h264",       "h263",        "h263p",         "h263i",
                 "h261",       "mpeg4",       "msmpeg4v3",     "msmpeg4v2",
                 "msmpeg4v1",  "wmv1",        "wmv2",          "dvvideo",
                 "mpeg1video", "mpeg2video",  "mjpeg",         "ljpeg",
                 "jpegls",     "avrn",        "huffyuv",       "ffvhuff",
                 "cyuv",       "rawvideo",    "frwu",          "r10k",
                 "r210",       "v210",        "v308",          "v408",
                 "v410",       "yuv4",        "indeo3",        "indeo4",
                 "indeo5",     "vp3",         "vp4",           "vp5",
                 "vp6",        "vp6a",        "vp6f",          "vp7",
                 "vp8",        "vp9",         "asv1",          "asv2",
                 "vcr1",       "ffv1",        "xan_wc4",       "mimic",
                 "msrle",      "msvideo1",    "cinepak",       "truemotion1",
                 "mszh",       "zlib",        "snow",          "4xm",
                 "flv1",       "flashsv",     "svq1",          "tscc",
                 "ulti",       "vixl",        "qpeg",          "wmv3",
                 "wmv3image",  "vc1",         "vc1image",      "loco",
                 "wnv1",       "aasc",        "indeo2",        "fraps",
                 "theora",     "truemotion2", "truemotion2rt", "cscd",
                 "zmbv",       "kmvc",        "cavs",          "avs2",
                 "jpeg2000",   "vmnc",        "targa",         "png",
                 "cljr",       "dirac",       "rpza",          "sp5x",
                 "aura",       "aura2",       "dpx",           "kgv1",
                 "lagarith",   "amv",         "utvideo",       "vble",
                 "escape130",  "dxtory",      "zerocodec",     "y41p",
                 "flic",       "mss1",        "msa1",          "tscc2",
                 "mts2",       "cllc",        "mss2",          "svq3",
                 "012v",       "g2m",         "fic",           "hqx",
                 "tdsc",       "hq_hqa",      "rv40",          "screenpresso",
                 "rscc",       "cfhd",        "m101",          "magicyuv",
                 "ylc",        "speedhq",     "fmvc",          "scpr",
                 "clearvideo", "av1",         "mscc",          "srgc",
                 "imm4",       "prosumer",    "mwsc",          "wcmv",
                 "rasc",       "hymt",        "arbc",          "agm",
                 "lscr",       "imm5",        "mvdv",          "mvha",
                 "mv30",       "notchlc",     "vqc",           "rtv1",
                 "vmix",       "lead",        "evc",           "rv60"}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis"}}}},
    {"avif", {{"video", {"av1"}}, {"audio", {}}}},
    {"avs", {{"video", {"avs2"}}, {"audio", {}}}},
    {"avs2", {{"video", {"avs2"}}, {"audio", {}}}},
    {"avs3", {{"video", {"avs3"}}, {"audio", {}}}},
    {"bit", {{"video", {}}, {"audio", {"g729"}}}},
    {"caf",
     {{"video", {}},
      {"audio",
       {"aac",       "ac3",       "adpcm_ima_qt", "adpcm_ima_wav", "adpcm_ms",
        "alac",      "amr_nb",    "gsm",          "gsm_ms",        "ilbc",
        "flac",      "mace3",     "mace6",        "mp1",           "mp2",
        "mp3",       "opus",      "pcm_alaw",     "pcm_mulaw",     "qcelp",
        "qdm2",      "qdmc",      "pcm_s8",       "pcm_s16le",     "pcm_s16be",
        "pcm_s24le", "pcm_s24be", "pcm_s32le",    "pcm_s32be",     "pcm_f32le",
        "pcm_f32be", "pcm_f64le", "pcm_f64be"}}}},
    {"cavs", {{"video", {"cavs"}}, {"audio", {}}}},
    {"c2", {{"video", {}}, {"audio", {"codec2"}}}},
    {"mpd", {{"video", {"h264"}}, {"audio", {"aac"}}}},
    {"302", {{"video", {}}, {"audio", {"pcm_s24daud"}}}},
    {"dfpwm", {{"video", {}}, {"audio", {"dfpwm"}}}},
    {"drc", {{"video", {"dirac"}}, {"audio", {}}}},
    {"vc2", {{"video", {"dirac"}}, {"audio", {}}}},
    {"dnxhd", {{"video", {"dnxhd"}}, {"audio", {}}}},
    {"dnxhr", {{"video", {"dnxhd"}}, {"audio", {}}}},
    {"dts", {{"video", {}}, {"audio", {"dts"}}}},
    {"dv", {{"video", {"dvvideo"}}, {"audio", {"pcm_s16le"}}}},
    {"eac3", {{"video", {}}, {"audio", {"eac3"}}}},
    {"ec3", {{"video", {}}, {"audio", {"eac3"}}}},
    {"evc", {{"video", {"evc"}}, {"audio", {}}}},
    {"f4v", {{"video", {"h264", "vp6a", "vp6f"}}, {"audio", {"mp3", "aac"}}}},
    {"ffmeta", {{"video", {}}, {"audio", {}}}},
    {"flm", {{"video", {"rawvideo"}}, {"audio", {}}}},
    {"fits", {{"video", {"fits"}}, {"audio", {}}}},
    {"flac", {{"video", {"png"}}, {"audio", {"flac"}}}},
    {"flv",
     {{"video",
       {"flv1", "h263", "mpeg4", "flashsv", "flashsv2", "vp6f", "vp6", "vp6a",
        "h264", "hevc", "vvc", "av1", "vp9"}},
      {"audio",
       {"mp3", "pcm_u8", "pcm_s16be", "pcm_s16le", "adpcm_swf", "aac",
        "nellymoser", "pcm_mulaw", "pcm_alaw", "speex", "opus", "flac", "ac3",
        "eac3"}}}},
    {"g722", {{"video", {}}, {"audio", {"adpcm_g722"}}}},
    {"tco", {{"video", {}}, {"audio", {"g723_1"}}}},
    {"rco", {{"video", {}}, {"audio", {"g723_1"}}}},
    {"gif", {{"video", {"gif"}}, {"audio", {}}}},
    {"gsm", {{"video", {}}, {"audio", {"gsm"}}}},
    {"gxf", {{"video", {"mpeg2video"}}, {"audio", {"pcm_s16le"}}}},
    {"h261", {{"video", {"h261"}}, {"audio", {}}}},
    {"h263", {{"video", {"h263"}}, {"audio", {}}}},
    {"h264", {{"video", {"h264"}}, {"audio", {}}}},
    {"264", {{"video", {"h264"}}, {"audio", {}}}},
    {"hevc", {{"video", {"hevc"}}, {"audio", {}}}},
    {"h265", {{"video", {"hevc"}}, {"audio", {}}}},
    {"265", {{"video", {"hevc"}}, {"audio", {}}}},
    {"m3u8", {{"video", {"h264"}}, {"audio", {"aac"}}}},
    {"iamf",
     {{"video", {}},
      {"audio",
       {"aac", "flac", "opus", "pcm_s16le", "pcm_s16be", "pcm_s24le",
        "pcm_s24be", "pcm_s32le", "pcm_s32be"}}}},
    {"ico", {{"video", {"bmp"}}, {"audio", {}}}},
    {"lbc", {{"video", {}}, {"audio", {"ilbc"}}}},
    {"bmp", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"dpx", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"exr", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"jls", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"jpeg", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"jpg", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"jxs", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"jxl", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"ljpg", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"pam", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"pbm", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"pcx", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"pfm", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"pgm", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"pgmyuv", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"phm", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"png", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"ppm", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"sgi", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"tga", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"tif", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"tiff", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"jp2", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"j2c", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"j2k", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"xwd", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"sun", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"ras", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"rs", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"im1", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"im8", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"im24", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"sunras", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"vbn", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"xbm", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"xface", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"pix", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"y", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"qoi", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"hdr", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"wbmp", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"m4v", {{"video", {"h264", "mpeg4"}}, {"audio", {"aac", "alac", "ac3"}}}},
    {"m4a", {{"video", {"h264", "mpeg4"}}, {"audio", {"aac", "alac", "ac3"}}}},
    {"m4b", {{"video", {"h264", "mpeg4"}}, {"audio", {"aac", "alac", "ac3"}}}},
    {"sf",
     {{"video", {}},
      {"audio",
       {"pcm_alaw", "pcm_f32le", "pcm_f64le", "pcm_mulaw", "pcm_s16le",
        "pcm_s24le", "pcm_s32le", "pcm_s8"}}}},
    {"ircam",
     {{"video", {}},
      {"audio",
       {"pcm_alaw", "pcm_f32le", "pcm_f64le", "pcm_mulaw", "pcm_s16le",
        "pcm_s24le", "pcm_s32le", "pcm_s8"}}}},
    {"ismv",
     {{"video",
       {"mpeg4", "h264", "hevc", "vvc", "evc", "apv", "mpeg2video",
        "mpeg1video", "mjpeg", "png", "jpeg2000", "vc1", "dirac", "tscc2",
        "vp9", "av1", "ffv1", "avs3"}},
      {"audio",
       {"aac",       "alac",      "mp4als",    "mp3",       "mp2",
        "ac3",       "eac3",      "dts",       "truehd",    "flac",
        "opus",      "vorbis",    "qcelp",     "evrc",      "mpegh_3d_audio",
        "pcm_s16be", "pcm_s16le", "pcm_s24be", "pcm_s24le", "pcm_s32be",
        "pcm_s32le", "pcm_f32be", "pcm_f32le", "pcm_f64be", "pcm_f64le",
        "wmapro"}}}},
    {"isma",
     {{"video",
       {"mpeg4", "h264", "hevc", "vvc", "evc", "apv", "mpeg2video",
        "mpeg1video", "mjpeg", "png", "jpeg2000", "vc1", "dirac", "tscc2",
        "vp9", "av1", "ffv1", "avs3"}},
      {"audio",
       {"aac",       "alac",      "mp4als",    "mp3",       "mp2",
        "ac3",       "eac3",      "dts",       "truehd",    "flac",
        "opus",      "vorbis",    "qcelp",     "evrc",      "mpegh_3d_audio",
        "pcm_s16be", "pcm_s16le", "pcm_s24be", "pcm_s24le", "pcm_s32be",
        "pcm_s32le", "pcm_f32be", "pcm_f32le", "pcm_f64be", "pcm_f64le",
        "wmapro"}}}},
    {"ivf", {{"video", {"vp8", "vp9", "av1"}}, {"audio", {}}}},
    {"jss", {{"video", {}}, {"audio", {}}}},
    {"js", {{"video", {}}, {"audio", {}}}},
    {"vag", {{"video", {}}, {"audio", {"adpcm_ima_ssi"}}}},
    {"latm", {{"video", {}}, {"audio", {"aac"}}}},
    {"loas", {{"video", {}}, {"audio", {"aac"}}}},
    {"lc3", {{"video", {}}, {"audio", {"lc3"}}}},
    {"lrc", {{"video", {}}, {"audio", {}}}},
    {"mcc", {{"video", {}}, {"audio", {}}}},
    {"mkv",
     {{"video", {"h264",       "h263",        "h263p",         "h263i",
                 "h261",       "mpeg4",       "msmpeg4v3",     "msmpeg4v2",
                 "msmpeg4v1",  "wmv1",        "wmv2",          "dvvideo",
                 "mpeg1video", "mpeg2video",  "mjpeg",         "ljpeg",
                 "jpegls",     "avrn",        "huffyuv",       "ffvhuff",
                 "cyuv",       "rawvideo",    "frwu",          "r10k",
                 "r210",       "v210",        "v308",          "v408",
                 "v410",       "yuv4",        "indeo3",        "indeo4",
                 "indeo5",     "vp3",         "vp4",           "vp5",
                 "vp6",        "vp6a",        "vp6f",          "vp7",
                 "vp8",        "vp9",         "asv1",          "asv2",
                 "vcr1",       "ffv1",        "xan_wc4",       "mimic",
                 "msrle",      "msvideo1",    "cinepak",       "truemotion1",
                 "mszh",       "zlib",        "snow",          "4xm",
                 "flv1",       "flashsv",     "svq1",          "tscc",
                 "ulti",       "vixl",        "qpeg",          "wmv3",
                 "wmv3image",  "vc1",         "vc1image",      "loco",
                 "wnv1",       "aasc",        "indeo2",        "fraps",
                 "theora",     "truemotion2", "truemotion2rt", "cscd",
                 "zmbv",       "kmvc",        "cavs",          "avs2",
                 "jpeg2000",   "vmnc",        "targa",         "png",
                 "cljr",       "dirac",       "rpza",          "sp5x",
                 "aura",       "aura2",       "dpx",           "kgv1",
                 "lagarith",   "amv",         "utvideo",       "vble",
                 "escape130",  "dxtory",      "zerocodec",     "y41p",
                 "flic",       "mss1",        "msa1",          "tscc2",
                 "mts2",       "cllc",        "mss2",          "svq3",
                 "012v",       "g2m",         "fic",           "hqx",
                 "tdsc",       "hq_hqa",      "rv40",          "screenpresso",
                 "rscc",       "cfhd",        "m101",          "magicyuv",
                 "ylc",        "speedhq",     "fmvc",          "scpr",
                 "clearvideo", "av1",         "mscc",          "srgc",
                 "imm4",       "prosumer",    "mwsc",          "wcmv",
                 "rasc",       "hymt",        "arbc",          "agm",
                 "lscr",       "imm5",        "mvdv",          "mvha",
                 "mv30",       "notchlc",     "vqc",           "rtv1",
                 "vmix",       "lead",        "evc",           "rv60"}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis",        "alac",          "atrac1",
                 "mlp",           "opus",          "pcm_s16be",
                 "pcm_s24be",     "pcm_s32be",     "qdmc",
                 "qdm2",          "ra_144",        "truehd"}}}},
    {"mka",
     {{"video", {}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis",        "alac",          "atrac1",
                 "mlp",           "opus",          "pcm_s16be",
                 "pcm_s24be",     "pcm_s32be",     "qdmc",
                 "qdm2",          "ra_144",        "truehd"}}}},
    {"sub", {{"video", {}}, {"audio", {}}}},
    {"mjpg", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"mjpeg", {{"video", {"mjpeg"}}, {"audio", {}}}},
    {"mlp", {{"video", {}}, {"audio", {"mlp"}}}},
    {"mmf", {{"video", {}}, {"audio", {"adpcm_yamaha"}}}},
    {"mov",
     {{"video", {"rawvideo", "r10k",       "r210",       "avui",       "avrp",
                 "v210",     "v308",       "v408",       "v410",       "y41p",
                 "yuv4",     "targa_y216", "mjpeg",      "mjpegb",     "svq1",
                 "svq3",     "mpeg4",      "h263",       "dvvideo",    "vp3",
                 "rpza",     "cinepak",    "8bps",       "smc",        "qtrle",
                 "sgirle",   "msrle",      "qdraw",      "cdtoons",    "vvc",
                 "hevc",     "h264",       "evc",        "vp8",        "vp9",
                 "av1",      "mpeg1video", "mpeg2video", "jpeg2000",   "targa",
                 "tiff",     "gif",        "png",        "vc1",        "cavs",
                 "dirac",    "dnxhd",      "msmpeg4v3",  "sgi",        "dpx",
                 "exr",      "prores",     "prores_raw", "flic",       "aic",
                 "hap",      "dxv",        "magicyuv",   "sheervideo", "pixlet",
                 "notchlc",  "media100",   "cfhd",       "lcevc",      "avs3",
                 "apv"}},
      {"audio",
       {"aac",       "ac3",           "ac4",        "adpcm_ima_qt", "alac",
        "amr_nb",    "amr_wb",        "dts",        "eac3",         "dvaudio",
        "gsm",       "ilbc",          "mace3",      "mace6",        "mp1",
        "mp2",       "mp3",           "nellymoser", "pcm_alaw",     "pcm_f32be",
        "pcm_f32le", "pcm_f64be",     "pcm_f64le",  "pcm_mulaw",    "pcm_s16be",
        "pcm_s16le", "pcm_s24be",     "pcm_s24le",  "pcm_s32be",    "pcm_s32le",
        "pcm_s8",    "pcm_u8",        "qcelp",      "qdm2",         "qdmc",
        "speex",     "evrc",          "smv",        "flac",         "truehd",
        "opus",      "mpegh_3d_audio"}}}},
    {"mp2", {{"video", {}}, {"audio", {"mp2"}}}},
    {"m2a", {{"video", {}}, {"audio", {"mp2"}}}},
    {"mpa", {{"video", {}}, {"audio", {"mp2"}}}},
    {"mp3", {{"video", {"png"}}, {"audio", {"mp3"}}}},
    {"mp4",
     {{"video",
       {"mpeg4", "h264", "hevc", "vvc", "evc", "apv", "mpeg2video",
        "mpeg1video", "mjpeg", "png", "jpeg2000", "vc1", "dirac", "tscc2",
        "vp9", "av1", "ffv1", "avs3"}},
      {"audio",
       {"aac",       "alac",      "mp4als",    "mp3",       "mp2",
        "ac3",       "eac3",      "dts",       "truehd",    "flac",
        "opus",      "vorbis",    "qcelp",     "evrc",      "mpegh_3d_audio",
        "pcm_s16be", "pcm_s16le", "pcm_s24be", "pcm_s24le", "pcm_s32be",
        "pcm_s32le", "pcm_f32be", "pcm_f32le", "pcm_f64be", "pcm_f64le"}}}},
    {"mpg", {{"video", {"mpeg1video"}}, {"audio", {"mp2"}}}},
    {"mpeg", {{"video", {"mpeg1video"}}, {"audio", {"mp2"}}}},
    {"m1v", {{"video", {"mpeg1video"}}, {"audio", {}}}},
    {"dvd", {{"video", {"mpeg2video"}}, {"audio", {"mp2"}}}},
    {"vob", {{"video", {"mpeg2video"}}, {"audio", {"mp2"}}}},
    {"m2v", {{"video", {"mpeg2video"}}, {"audio", {}}}},
    {"ts", {{"video", {"mpeg2video"}}, {"audio", {"mp2"}}}},
    {"m2t", {{"video", {"mpeg2video"}}, {"audio", {"mp2"}}}},
    {"m2ts", {{"video", {"mpeg2video"}}, {"audio", {"mp2"}}}},
    {"mts", {{"video", {"mpeg2video"}}, {"audio", {"mp2"}}}},
    {"mxf", {{"video", {"mpeg2video"}}, {"audio", {"pcm_s16le"}}}},
    {"nut",
     {{"video", {"gif",        "xface",       "vp9",           "hevc",
                 "cpia",       "rawvideo",    "h264",          "h263",
                 "h263p",      "h263i",       "h261",          "mpeg4",
                 "msmpeg4v3",  "msmpeg4v2",   "msmpeg4v1",     "wmv1",
                 "wmv2",       "dvvideo",     "mpeg1video",    "mpeg2video",
                 "mjpeg",      "ljpeg",       "jpegls",        "avrn",
                 "huffyuv",    "ffvhuff",     "cyuv",          "frwu",
                 "r10k",       "r210",        "v210",          "v308",
                 "v408",       "v410",        "yuv4",          "indeo3",
                 "indeo4",     "indeo5",      "vp3",           "vp4",
                 "vp5",        "vp6",         "vp6a",          "vp6f",
                 "vp7",        "vp8",         "asv1",          "asv2",
                 "vcr1",       "ffv1",        "xan_wc4",       "mimic",
                 "msrle",      "msvideo1",    "cinepak",       "truemotion1",
                 "mszh",       "zlib",        "snow",          "4xm",
                 "flv1",       "flashsv",     "svq1",          "tscc",
                 "ulti",       "vixl",        "qpeg",          "wmv3",
                 "wmv3image",  "vc1",         "vc1image",      "loco",
                 "wnv1",       "aasc",        "indeo2",        "fraps",
                 "theora",     "truemotion2", "truemotion2rt", "cscd",
                 "zmbv",       "kmvc",        "cavs",          "avs2",
                 "jpeg2000",   "vmnc",        "targa",         "png",
                 "cljr",       "dirac",       "rpza",          "sp5x",
                 "aura",       "aura2",       "dpx",           "kgv1",
                 "lagarith",   "amv",         "utvideo",       "vble",
                 "escape130",  "dxtory",      "zerocodec",     "y41p",
                 "flic",       "mss1",        "msa1",          "tscc2",
                 "mts2",       "cllc",        "mss2",          "svq3",
                 "012v",       "g2m",         "fic",           "hqx",
                 "tdsc",       "hq_hqa",      "rv40",          "screenpresso",
                 "rscc",       "cfhd",        "m101",          "magicyuv",
                 "ylc",        "speedhq",     "fmvc",          "scpr",
                 "clearvideo", "av1",         "mscc",          "srgc",
                 "imm4",       "prosumer",    "mwsc",          "wcmv",
                 "rasc",       "hymt",        "arbc",          "agm",
                 "lscr",       "imm5",        "mvdv",          "mvha",
                 "mv30",       "notchlc",     "vqc",           "rtv1",
                 "vmix",       "lead",        "evc",           "rv60"}},
      {"audio",
       {"pcm_f32be",
        "pcm_f32le",
        "pcm_f64be",
        "pcm_f64le",
        "pcm_s16be",
        "pcm_s16le",
        "pcm_s24be",
        "pcm_s24le",
        "pcm_s32be",
        "pcm_s32le",
        "pcm_s64be",
        "pcm_s64le",
        "pcm_s8",
        "pcm_u16be",
        "pcm_u16le",
        "pcm_u24be",
        "pcm_u24le",
        "pcm_u32be",
        "pcm_u32le",
        "pcm_u8",
        "pcm_s8_planar",
        "pcm_s16be_planar",
        "pcm_s16le_planar",
        "pcm_s24le_planar",
        "pcm_s32le_planar",
        "adpcm_ms",
        "pcm_alaw",
        "pcm_mulaw",
        "wmavoice",
        "adpcm_ima_oki",
        "adpcm_ima_wav",
        "adpcm_zork",
        "adpcm_yamaha",
        "truespeech",
        "gsm_ms",
        "amr_nb",
        "g723_1",
        "adpcm_g726",
        "g728",
        "mp2",
        "mp3",
        "amr_wb",
        "adpcm_ima_dk4",
        "adpcm_ima_dk3",
        "adpcm_ima_xbox",
        "metasound",
        "g729",
        "aac",
        "adpcm_sanyo",
        "sipr",
        "acelp.kelvin",
        "wmav1",
        "wmav2",
        "wmapro",
        "wmalossless",
        "xma1",
        "xma2",
        "ftr",
        "adpcm_ct",
        "dvaudio",
        "atrac3",
        "msnsiren",
        "adpcm_g722",
        "misc4",
        "imc",
        "iac",
        "avc",
        "aac_latm",
        "ac3",
        "eac3",
        "dts",
        "sonic",
        "sonicls",
        "xan_dpcm",
        "speex",
        "flac",
        "dfpwm",
        "adpcm_swf",
        "vorbis",
        "comfortnoise",
        "opus",
        "wavpack"}}}},
    {"obu", {{"video", {"av1"}}, {"audio", {}}}},
    {"oga", {{"video", {}}, {"audio", {"flac"}}}},
    {"ogg", {{"video", {"theora"}}, {"audio", {"vorbis"}}}},
    {"ogv", {{"video", {"theora"}}, {"audio", {"vorbis"}}}},
    {"oma",
     {{"video", {}},
      {"audio",
       {"atrac3", "atrac3p", "aac", "mp3", "pcm_s16be", "atrac3pal",
        "atrac3al"}}}},
    {"opus", {{"video", {}}, {"audio", {"opus"}}}},
    {"al", {{"video", {}}, {"audio", {"pcm_alaw"}}}},
    {"ul", {{"video", {}}, {"audio", {"pcm_mulaw"}}}},
    {"sw", {{"video", {}}, {"audio", {"pcm_s16le"}}}},
    {"sb", {{"video", {}}, {"audio", {"pcm_s8"}}}},
    {"uw", {{"video", {}}, {"audio", {"pcm_u16le"}}}},
    {"ub", {{"video", {}}, {"audio", {"pcm_u8"}}}},
    {"psp",
     {{"video",
       {"mpeg4", "h264", "hevc", "vvc", "evc", "apv", "mpeg2video",
        "mpeg1video", "mjpeg", "png", "jpeg2000", "vc1", "dirac", "tscc2",
        "vp9", "av1", "ffv1", "avs3"}},
      {"audio",
       {"aac",       "alac",      "mp4als",    "mp3",       "mp2",
        "ac3",       "eac3",      "dts",       "truehd",    "flac",
        "opus",      "vorbis",    "qcelp",     "evrc",      "mpegh_3d_audio",
        "pcm_s16be", "pcm_s16le", "pcm_s24be", "pcm_s24le", "pcm_s32be",
        "pcm_s32le", "pcm_f32be", "pcm_f32le", "pcm_f64be", "pcm_f64le"}}}},
    {"yuv", {{"video", {"rawvideo"}}, {"audio", {}}}},
    {"rgb", {{"video", {"rawvideo"}}, {"audio", {}}}},
    {"rm",
     {{"video", {"rv10", "rv20", "rv30", "rv40", "rv60", "clearvideo"}},
      {"audio",
       {"ac3", "ra_144", "ra_288", "cook", "atrac3", "sipr", "aac", "ralf"}}}},
    {"ra",
     {{"video", {"rv10", "rv20", "rv30", "rv40", "rv60", "clearvideo"}},
      {"audio",
       {"ac3", "ra_144", "ra_288", "cook", "atrac3", "sipr", "aac", "ralf"}}}},
    {"roq", {{"video", {"roq"}}, {"audio", {"roq_dpcm"}}}},
    {"rso", {{"video", {}}, {"audio", {"pcm_u8", "adpcm_ima_wav"}}}},
    {"sbc", {{"video", {}}, {"audio", {"sbc"}}}},
    {"msbc", {{"video", {}}, {"audio", {"sbc"}}}},
    {"scc", {{"video", {}}, {"audio", {}}}},
    {"cpk", {{"video", {"cinepak"}}, {"audio", {"pcm_s16be_planar"}}}},
    {"sox", {{"video", {}}, {"audio", {"pcm_s32le"}}}},
    {"spx", {{"video", {}}, {"audio", {"speex"}}}},
    {"spdif", {{"video", {}}, {"audio", {"ac3"}}}},
    {"srt", {{"video", {}}, {"audio", {}}}},
    {"sup", {{"video", {}}, {"audio", {}}}},
    {"swf", {{"video", {"flv1"}}, {"audio", {"mp3"}}}},
    {"3g2",
     {{"video", {"h263", "h264", "mpeg4"}},
      {"audio", {"aac", "amr_nb", "amr_wb"}}}},
    {"3gp",
     {{"video", {"h263", "h264", "mpeg4"}},
      {"audio", {"aac", "amr_nb", "amr_wb"}}}},
    {"thd", {{"video", {}}, {"audio", {"truehd"}}}},
    {"tta", {{"video", {}}, {"audio", {"tta"}}}},
    {"ttml", {{"video", {}}, {"audio", {}}}},
    {"vc1", {{"video", {"vc1"}}, {"audio", {}}}},
    {"rcv", {{"video", {"wmv3"}}, {"audio", {}}}},
    {"voc",
     {{"video", {}},
      {"audio",
       {"pcm_u8", "adpcm_sbpro_4", "adpcm_sbpro_3", "adpcm_sbpro_2",
        "pcm_s16le", "pcm_alaw", "pcm_mulaw", "adpcm_ct"}}}},
    {"vvc", {{"video", {"vvc"}}, {"audio", {}}}},
    {"h266", {{"video", {"vvc"}}, {"audio", {}}}},
    {"266", {{"video", {"vvc"}}, {"audio", {}}}},
    {"w64",
     {{"video", {}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis"}}}},
    {"wav",
     {{"video", {}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis"}}}},
    {"webm", {{"video", {"vp9"}}, {"audio", {"opus"}}}},
    {"xml", {{"video", {}}, {"audio", {}}}},
    {"chk", {{"video", {}}, {"audio", {}}}},
    {"webp", {{"video", {"webp"}}, {"audio", {}}}},
    {"vtt", {{"video", {}}, {"audio", {}}}},
    {"aud", {{"video", {}}, {"audio", {"adpcm_ima_ws"}}}},
    {"wtv",
     {{"video", {"h264",       "h263",        "h263p",         "h263i",
                 "h261",       "mpeg4",       "msmpeg4v3",     "msmpeg4v2",
                 "msmpeg4v1",  "wmv1",        "wmv2",          "dvvideo",
                 "mpeg1video", "mpeg2video",  "mjpeg",         "ljpeg",
                 "jpegls",     "avrn",        "huffyuv",       "ffvhuff",
                 "cyuv",       "rawvideo",    "frwu",          "r10k",
                 "r210",       "v210",        "v308",          "v408",
                 "v410",       "yuv4",        "indeo3",        "indeo4",
                 "indeo5",     "vp3",         "vp4",           "vp5",
                 "vp6",        "vp6a",        "vp6f",          "vp7",
                 "vp8",        "vp9",         "asv1",          "asv2",
                 "vcr1",       "ffv1",        "xan_wc4",       "mimic",
                 "msrle",      "msvideo1",    "cinepak",       "truemotion1",
                 "mszh",       "zlib",        "snow",          "4xm",
                 "flv1",       "flashsv",     "svq1",          "tscc",
                 "ulti",       "vixl",        "qpeg",          "wmv3",
                 "wmv3image",  "vc1",         "vc1image",      "loco",
                 "wnv1",       "aasc",        "indeo2",        "fraps",
                 "theora",     "truemotion2", "truemotion2rt", "cscd",
                 "zmbv",       "kmvc",        "cavs",          "avs2",
                 "jpeg2000",   "vmnc",        "targa",         "png",
                 "cljr",       "dirac",       "rpza",          "sp5x",
                 "aura",       "aura2",       "dpx",           "kgv1",
                 "lagarith",   "amv",         "utvideo",       "vble",
                 "escape130",  "dxtory",      "zerocodec",     "y41p",
                 "flic",       "mss1",        "msa1",          "tscc2",
                 "mts2",       "cllc",        "mss2",          "svq3",
                 "012v",       "g2m",         "fic",           "hqx",
                 "tdsc",       "hq_hqa",      "rv40",          "screenpresso",
                 "rscc",       "cfhd",        "m101",          "magicyuv",
                 "ylc",        "speedhq",     "fmvc",          "scpr",
                 "clearvideo", "av1",         "mscc",          "srgc",
                 "imm4",       "prosumer",    "mwsc",          "wcmv",
                 "rasc",       "hymt",        "arbc",          "agm",
                 "lscr",       "imm5",        "mvdv",          "mvha",
                 "mv30",       "notchlc",     "vqc",           "rtv1",
                 "vmix",       "lead",        "evc",           "rv60"}},
      {"audio", {"pcm_s16le",     "pcm_u8",        "pcm_s24le",
                 "pcm_s32le",     "pcm_s64le",     "adpcm_ms",
                 "pcm_f32le",     "pcm_f64le",     "pcm_alaw",
                 "pcm_mulaw",     "wmavoice",      "adpcm_ima_oki",
                 "adpcm_ima_wav", "adpcm_zork",    "adpcm_yamaha",
                 "truespeech",    "gsm_ms",        "amr_nb",
                 "g723_1",        "adpcm_g726",    "g728",
                 "mp2",           "mp3",           "amr_wb",
                 "adpcm_ima_dk4", "adpcm_ima_dk3", "adpcm_ima_xbox",
                 "metasound",     "g729",          "aac",
                 "adpcm_sanyo",   "sipr",          "acelp.kelvin",
                 "wmav1",         "wmav2",         "wmapro",
                 "wmalossless",   "xma1",          "xma2",
                 "ftr",           "adpcm_ct",      "dvaudio",
                 "atrac3",        "msnsiren",      "adpcm_g722",
                 "misc4",         "imc",           "iac",
                 "avc",           "aac_latm",      "ac3",
                 "eac3",          "dts",           "sonic",
                 "sonicls",       "xan_dpcm",      "speex",
                 "flac",          "dfpwm",         "adpcm_swf",
                 "vorbis"}}}},
    {"wv", {{"video", {}}, {"audio", {"wavpack"}}}},
    {"y4m", {{"video", {"wrapped_avframe"}}, {"audio", {}}}}};

#endif // CODEC_DESCRIPTORS_H
